# Generated by Django 4.0.2 on 2022-03-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_conference_timedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
    ]
