# Generated by Django 4.0.2 on 2022-03-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='media',
            field=models.ImageField(null=True, upload_to='users_media/education'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='researchpapers',
            name='media',
            field=models.FileField(null=True, upload_to='users_media/research_papers'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='media',
            field=models.ImageField(max_length=200, null=True, upload_to='users_media/thread_media'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='users_media/pictures'),
        ),
        migrations.AlterField(
            model_name='workexp',
            name='media',
            field=models.ImageField(null=True, upload_to='users_media/workexp'),
        ),
    ]
