# Generated by Django 4.0.2 on 2022-03-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_education_end_date_alter_education_media_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userresearch',
            old_name='research_id',
            new_name='research',
        ),
        migrations.RenameField(
            model_name='userresearch',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='workexp',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='education',
            name='media',
            field=models.FileField(null=True, upload_to='users_media/education'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='media',
            field=models.FileField(max_length=200, null=True, upload_to='users_media/thread_media'),
        ),
        migrations.AlterField(
            model_name='workexp',
            name='employment_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workexp',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workexp',
            name='media',
            field=models.FileField(null=True, upload_to='users_media/workexp'),
        ),
        migrations.AlterField(
            model_name='workexp',
            name='ongoing',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='workexp',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
