# Generated by Django 4.0.2 on 2022-03-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_certification_user_remove_education_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.IntegerField()),
                ('dates', models.DateTimeField()),
                ('address', models.TextField(null=True)),
                ('event_name', models.CharField(max_length=200)),
                ('media', models.ImageField(null=True, upload_to='', verbose_name='events/')),
                ('domain', models.TextField()),
                ('website', models.TextField(null=True)),
            ],
        ),
    ]
