# Generated by Django 4.0.2 on 2022-03-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('event_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='media_1',
            field=models.ImageField(null=True, upload_to='', verbose_name='events/media1'),
        ),
        migrations.AddField(
            model_name='events',
            name='media_2',
            field=models.ImageField(null=True, upload_to='', verbose_name='events/media2'),
        ),
        migrations.AddField(
            model_name='events',
            name='media_3',
            field=models.ImageField(null=True, upload_to='', verbose_name='events/media3'),
        ),
        migrations.AddField(
            model_name='events',
            name='media_4',
            field=models.ImageField(null=True, upload_to='', verbose_name='events/media4'),
        ),
        migrations.AddField(
            model_name='events',
            name='save',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='speaker',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='verify',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='domain',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='media',
            field=models.ImageField(null=True, upload_to='', verbose_name='events/media'),
        ),
    ]
