# Generated by Django 4.0.2 on 2022-03-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userevent_events_media_1_events_media_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedResearchPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('research_id', models.IntegerField(null=True)),
            ],
        ),
    ]
