# Generated by Django 4.0.2 on 2022-03-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_savedresearchpapers'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='pdf',
            field=models.FileField(null=True, upload_to='', verbose_name='events/pdf'),
        ),
    ]
