# Generated by Django 4.0.2 on 2022-03-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_events_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='contact_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_details',
            field=models.TextField(null=True),
        ),
    ]
