# Generated by Django 4.0.2 on 2022-03-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_events_contact_number_events_event_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='save',
            new_name='saves',
        ),
    ]
