# Generated by Django 4.0.2 on 2022-03-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_events_contact_number_events_event_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpapers',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
