# Generated by Django 4.0.2 on 2022-03-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_save_events_saves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='media',
            field=models.ImageField(null=True, upload_to='events/media'),
        ),
        migrations.AlterField(
            model_name='events',
            name='media_1',
            field=models.ImageField(null=True, upload_to='events/media1'),
        ),
        migrations.AlterField(
            model_name='events',
            name='media_2',
            field=models.ImageField(null=True, upload_to='events/media2'),
        ),
        migrations.AlterField(
            model_name='events',
            name='media_3',
            field=models.ImageField(null=True, upload_to='events/media3'),
        ),
        migrations.AlterField(
            model_name='events',
            name='media_4',
            field=models.ImageField(null=True, upload_to='events/media4'),
        ),
        migrations.AlterField(
            model_name='events',
            name='pdf',
            field=models.FileField(null=True, upload_to='events/pdf'),
        ),
    ]
