# Generated by Django 4.0.2 on 2022-03-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_users_github_users_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='organization_name',
            field=models.TextField(null=True),
        ),
    ]
