# Generated by Django 4.0.2 on 2022-03-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_events_media_alter_events_media_1_and_more'),
        ('users', '0014_alter_users_description_and_more'),
    ]

    operations = [
    ]
