# Generated by Django 4.0.2 on 2022-03-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20220313_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=300)),
                ('journal_name', models.CharField(max_length=300)),
                ('image_url', models.TextField(null=True)),
                ('aim', models.TextField(null=True)),
                ('period', models.CharField(max_length=100)),
                ('issn', models.CharField(max_length=150)),
                ('journal_link', models.TextField(null=True)),
                ('editor', models.TextField(null=True)),
                ('impact_score', models.FloatField(null=True)),
                ('impact_factor', models.FloatField(null=True)),
                ('sjr', models.FloatField(null=True)),
                ('cite', models.FloatField(null=True)),
                ('h_index', models.FloatField(null=True)),
                ('ranking', models.IntegerField(null=True)),
                ('top_scientist', models.IntegerField(null=True)),
                ('top_docs', models.IntegerField(null=True)),
                ('saves', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('journal_id', models.IntegerField(null=True)),
            ],
        ),
    ]
