# Generated by Django 4.0.2 on 2022-03-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20220313_1910'),
        ('users', '0016_journals_journalsuser'),
    ]

    operations = [
    ]
