# Generated by Django 4.0.2 on 2022-03-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('domain', models.CharField(max_length=500, null=True)),
                ('skills', models.CharField(max_length=500, null=True)),
                ('media', models.FileField(null=True, upload_to='users_media/collabfiles')),
                ('duration', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(null=True)),
                ('collabrequest', models.IntegerField(null=True)),
                ('cover_letter', models.TextField()),
                ('media', models.FileField(null=True, upload_to='users_media/proposalfiles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
